package org.eclipse.jet.compiled;

import org.eclipse.jet.JET2Context;
import org.eclipse.jet.JET2Template;
import org.eclipse.jet.JET2Writer;
import org.eclipse.jet.taglib.RuntimeTagElement;
import org.eclipse.jet.taglib.TagInfo;

public class _jet_Logesql implements JET2Template {
    private static final String _jetns_c = "org.eclipse.jet.controlTags"; //$NON-NLS-1$

    public _jet_Logesql() {
        super();
    }

    private static final String NL = System.getProperty("line.separator"); //$NON-NLS-1$
    
    private static final TagInfo _td_c_if_1_1 = new TagInfo("c:if", //$NON-NLS-1$
            1, 1,
            new String[] {
                "test", //$NON-NLS-1$
            },
            new String[] {
                "boolean($root/brokerSchema)", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_if_3_1 = new TagInfo("c:if", //$NON-NLS-1$
            3, 1,
            new String[] {
                "test", //$NON-NLS-1$
            },
            new String[] {
                "string-length($root/brokerSchema) > 0", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_get_5_15 = new TagInfo("c:get", //$NON-NLS-1$
            5, 15,
            new String[] {
                "select", //$NON-NLS-1$
            },
            new String[] {
                "$root/brokerSchema", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_get_8_18 = new TagInfo("c:get", //$NON-NLS-1$
            8, 18,
            new String[] {
                "select", //$NON-NLS-1$
            },
            new String[] {
                "$root/@patternName", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_get_8_63 = new TagInfo("c:get", //$NON-NLS-1$
            8, 63,
            new String[] {
                "select", //$NON-NLS-1$
            },
            new String[] {
                "$root/@patternVersion", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_get_9_23 = new TagInfo("c:get", //$NON-NLS-1$
            9, 23,
            new String[] {
                "select", //$NON-NLS-1$
            },
            new String[] {
                "$root/@patternName", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_get_10_26 = new TagInfo("c:get", //$NON-NLS-1$
            10, 26,
            new String[] {
                "select", //$NON-NLS-1$
            },
            new String[] {
                "$root/@patternVersion", //$NON-NLS-1$
            } );

    public void generate(final JET2Context context, final JET2Writer __out) {
        JET2Writer out = __out;
        RuntimeTagElement _jettag_c_if_1_1 = context.getTagFactory().createRuntimeTag(_jetns_c, "if", "c:if", _td_c_if_1_1); //$NON-NLS-1$ //$NON-NLS-2$
        _jettag_c_if_1_1.setRuntimeParent(null);
        _jettag_c_if_1_1.setTagInfo(_td_c_if_1_1);
        _jettag_c_if_1_1.doStart(context, out);
        while (_jettag_c_if_1_1.okToProcessBody()) {
            // Tag exists 
            RuntimeTagElement _jettag_c_if_3_1 = context.getTagFactory().createRuntimeTag(_jetns_c, "if", "c:if", _td_c_if_3_1); //$NON-NLS-1$ //$NON-NLS-2$
            _jettag_c_if_3_1.setRuntimeParent(_jettag_c_if_1_1);
            _jettag_c_if_3_1.setTagInfo(_td_c_if_3_1);
            _jettag_c_if_3_1.doStart(context, out);
            while (_jettag_c_if_3_1.okToProcessBody()) {
                // and has a value
                out.write("BROKER SCHEMA ");  //$NON-NLS-1$        
                RuntimeTagElement _jettag_c_get_5_15 = context.getTagFactory().createRuntimeTag(_jetns_c, "get", "c:get", _td_c_get_5_15); //$NON-NLS-1$ //$NON-NLS-2$
                _jettag_c_get_5_15.setRuntimeParent(_jettag_c_if_3_1);
                _jettag_c_get_5_15.setTagInfo(_td_c_get_5_15);
                _jettag_c_get_5_15.doStart(context, out);
                _jettag_c_get_5_15.doEnd();
                out.write(NL);         
                _jettag_c_if_3_1.handleBodyContent(out);
            }
            _jettag_c_if_3_1.doEnd();
            _jettag_c_if_1_1.handleBodyContent(out);
        }
        _jettag_c_if_1_1.doEnd();
        out.write("--  Generated by ");  //$NON-NLS-1$        
        RuntimeTagElement _jettag_c_get_8_18 = context.getTagFactory().createRuntimeTag(_jetns_c, "get", "c:get", _td_c_get_8_18); //$NON-NLS-1$ //$NON-NLS-2$
        _jettag_c_get_8_18.setRuntimeParent(null);
        _jettag_c_get_8_18.setTagInfo(_td_c_get_8_18);
        _jettag_c_get_8_18.doStart(context, out);
        _jettag_c_get_8_18.doEnd();
        out.write(" Version ");  //$NON-NLS-1$        
        RuntimeTagElement _jettag_c_get_8_63 = context.getTagFactory().createRuntimeTag(_jetns_c, "get", "c:get", _td_c_get_8_63); //$NON-NLS-1$ //$NON-NLS-2$
        _jettag_c_get_8_63.setRuntimeParent(null);
        _jettag_c_get_8_63.setTagInfo(_td_c_get_8_63);
        _jettag_c_get_8_63.doStart(context, out);
        _jettag_c_get_8_63.doEnd();
        out.write(NL);         
        out.write("--  $MQSI patternName=");  //$NON-NLS-1$        
        RuntimeTagElement _jettag_c_get_9_23 = context.getTagFactory().createRuntimeTag(_jetns_c, "get", "c:get", _td_c_get_9_23); //$NON-NLS-1$ //$NON-NLS-2$
        _jettag_c_get_9_23.setRuntimeParent(null);
        _jettag_c_get_9_23.setTagInfo(_td_c_get_9_23);
        _jettag_c_get_9_23.doStart(context, out);
        _jettag_c_get_9_23.doEnd();
        out.write(" MQSI$");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("--  $MQSI patternVersion=");  //$NON-NLS-1$        
        RuntimeTagElement _jettag_c_get_10_26 = context.getTagFactory().createRuntimeTag(_jetns_c, "get", "c:get", _td_c_get_10_26); //$NON-NLS-1$ //$NON-NLS-2$
        _jettag_c_get_10_26.setRuntimeParent(null);
        _jettag_c_get_10_26.setTagInfo(_td_c_get_10_26);
        _jettag_c_get_10_26.doStart(context, out);
        _jettag_c_get_10_26.doEnd();
        out.write(" MQSI$");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("DECLARE RequestLoggingOn EXTERNAL BOOLEAN TRUE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("DECLARE ResponseLoggingOn EXTERNAL BOOLEAN TRUE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("CREATE Filter MODULE CheckLogging");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("\tCREATE FUNCTION main() RETURNS BOOLEAN BEGIN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tIF LocalEnvironment.Variables.StatusCode = 1 ");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tTHEN RETURN RequestLoggingOn;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tELSE RETURN ResponseLoggingOn;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tEND IF;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tEND;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tEND MODULE;\t");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write(NL);         
        out.write(NL);         
        out.write("\tCREATE Compute MODULE CreateLogMessage");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tCREATE FUNCTION main() RETURNS BOOLEAN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tBEGIN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutputRoot.Properties = NULL;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tCREATE FIRSTCHILD OF OutputRoot DOMAIN ('MQMD') NAME 'MQMD';");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tDECLARE MQMDRef REFERENCE TO OutputRoot.MQMD;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET MQMDRef.Format = MQFMT_RF_HEADER_2;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET MQMDRef.Version = MQMD_CURRENT_VERSION;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET MQMDRef.CodedCharSetId = InputRoot.Properties.CodedCharSetId;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET MQMDRef.Encoding = InputRoot.Properties.Encoding;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tDECLARE OutRef REFERENCE TO OutputRoot;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tCREATE NEXTSIBLING OF MQMDRef AS OutRef DOMAIN('MQRFH2') NAME 'MQRFH2';");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutputRoot.MQRFH2.(MQRFH2.Field)Version = 2;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutRef.usr.BrokerName = SQL.BrokerName;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tMove OutRef TO OutRef.usr;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutRef.MessageFlowLabel = SQL.MessageFlowLabel;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutRef.DTSTAMP = CURRENT_TIMESTAMP;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\t-- Add service information");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutRef.StatusCode = InputLocalEnvironment.Variables.StatusCode;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutRef.ServiceName = InputRoot.SOAP.Context.service;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutRef.ServiceNameSpace = InputRoot.SOAP.Context.Namespace;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutRef.ServicePort = InputRoot.SOAP.Context.port;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutRef.ServicePortType = InputRoot.SOAP.Context.portType;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutRef.ServiceOperation = InputRoot.SOAP.Context.operation;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutRef.ServiceTargetEndpoint = Environment.PatternVariables.TargetEndpoint;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutRef.ServiceSOAPVersion = InputRoot.SOAP.Context.SOAP_Version;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tCREATE NEXTSIBLING OF OutputRoot.MQRFH2 DOMAIN('XMLNSC') NAME 'XMLNSC';");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\t-- Log SOAP data in XMLNSC body");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutputRoot.XMLNSC.Message = InputBody;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tEND;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tEND MODULE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write(NL);         
        out.write("\tCREATE Compute MODULE CreateTraceData");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tCREATE FUNCTION main() RETURNS BOOLEAN BEGIN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tDECLARE EnvVarRef REFERENCE TO Environment.PatternVariables;\t");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("\t\t\tSET EnvVarRef.DTSTAMP = CURRENT_TIMESTAMP;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET EnvVarRef.BrokerName = SQL.BrokerName;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET EnvVarRef.MessageFlowlabel = SQL.MessageFlowLabel;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET EnvVarRef.Action = InputRoot.SOAP.Context.operation;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\t-- Add service information");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET EnvVarRef.Service.(XMLNSC.PCDataField)name = InputRoot.SOAP.Context.service;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET EnvVarRef.Service.nameSpace = InputRoot.SOAP.Context.Namespace;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET EnvVarRef.Service.(XMLNSC.PCDataField)port = InputRoot.SOAP.Context.port;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET EnvVarRef.Service.(XMLNSC.PCDataField)portType = InputRoot.SOAP.Context.portType;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET EnvVarRef.Service.(XMLNSC.PCDataField)operation = InputRoot.SOAP.Context.operation;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET EnvVarRef.Service.(XMLNSC.PCDataField)targetEndpoint = Environment.PatternVariables.TargetEndpoint;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET EnvVarRef.Service.(XMLNSC.PCDataField)SOAPVersion = InputRoot.SOAP.Context.SOAP_Version;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("\t\tEND;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tEND MODULE;");  //$NON-NLS-1$        
    }
}
